# nixpacks.toml

# Define the setup phase where system packages are installed
[phases.setup]
# Only essential build tools needed for Python packages (if any have C extensions)
# No longer need ffmpeg, libsodium-dev, libopus0, python3-dev as music system is removed.
aptPkgs = ["build-essential"]
